#!/bin/bash

echo "=========================================="
echo "Splitwise MCP Balance Calculation Demo"
echo "=========================================="
echo ""
echo "Scenario: 5-member group with unequal payments"
echo ""
echo "Expenses:"
echo "  Member 1: \$50 (Booking)"
echo "  Member 2: \$300 (Food)"
echo "  Member 3: \$100 (Drinks)"
echo "  Member 4: \$20 (Utensils)"
echo "  Member 5: \$0 (Nothing)"
echo ""
echo "Total: \$470"
echo "Per person: \$94"
echo ""
echo "=========================================="
echo "BALANCES"
echo "=========================================="
echo ""
echo "Member 1: Paid \$50  | Owes \$94  | Balance: -\$44  💸"
echo "Member 2: Paid \$300 | Owes \$94  | Balance: +\$206 💚"
echo "Member 3: Paid \$100 | Owes \$94  | Balance: +\$6   💚"
echo "Member 4: Paid \$20  | Owes \$94  | Balance: -\$74  💸"
echo "Member 5: Paid \$0   | Owes \$94  | Balance: -\$94  💸"
echo ""
echo "=========================================="
echo "SETTLEMENT PLAN"
echo "=========================================="
echo ""
echo "1. Member 5 → Member 2: \$94.00"
echo "2. Member 4 → Member 2: \$74.00"
echo "3. Member 1 → Member 2: \$38.00"
echo "4. Member 1 → Member 3: \$6.00"
echo ""
echo "✅ All balances settled with 4 transactions!"
echo ""
echo "=========================================="
echo "To test with Splitwise MCP:"
echo "=========================================="
echo ""
echo "Option 1: Run the Node.js test script"
echo "  $ node test_splitwise_balance.js"
echo ""
echo "Option 2: Use via WhatsApp bot"
echo "  @anukul split expense \$50 booking @member1 @member2 @member3 @member4 @member5"
echo "  @anukul split expense \$300 food @member1 @member2 @member3 @member4 @member5"
echo "  @anukul split expense \$100 drinks @member1 @member2 @member3 @member4 @member5"
echo "  @anukul split expense \$20 utensils @member1 @member2 @member3 @member4 @member5"
echo "  @anukul balance"
echo ""
echo "=========================================="
